- name: Install Apache, set timezone, and deploy HTML page
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache
      package:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Deploy HTML page
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == "RedHat"
